version: "3.1"
services:
  wordpress:
    build: ./wordpress
    container_name: "owell_wordpress"
    ports:
      - "9000:80"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: "mariadb:3306"
    volumes:
      - ./public:/var/www/html/wp-content/themes/owell
      - ./Movefile:/var/www/html/Movefile
  mariadb:
    container_name: "owell_db"
    image: mariadb:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
      # - ./database/install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
  wordmove:
    container_name: "owell_wordmove"
    image: welaika/wordmove:latest
volumes:
  db-data:
    driver: local
